fbt: moved environment init to scripts/toolchain; skipping environment init if FBT_NOENV is set in environment

diff --git a/fbt b/fbt
--- a/fbt
+++ b/fbt
@@ -1,61 +1,13 @@
 #!/bin/sh
-# shellcheck disable=SC2086
+SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)";
+. $SCRIPT_PATH/scripts/toolchain/fbtenv.sh;
 
-# unofficial strict mode
-set -eu;
+if [ ! -d "${FBT_ROOT:-.}/.git" ]; then
+    echo "\".git\" directory not found, please clone repo via \"git clone --recursive\"";
+    exit 1;
+fi
 
-FLIPPER_TOOLCHAIN_VERSION="2";
-SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)"
-SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built";
-
-get_kernel_type()
-{
-    SYS_TYPE="$(uname -s)"
-    if [ "$SYS_TYPE" = "Darwin" ]; then
-        TOOLCHAIN_PATH="toolchain/x86_64-darwin";
-    elif [ "$SYS_TYPE" = "Linux" ]; then
-        TOOLCHAIN_PATH="toolchain/x86_64-linux";
-    elif echo "$SYS_TYPE" | grep -q "MINGW"; then
-        echo "In MinGW shell use \"fbt.cmd\" instead of \"fbt\"";
-        exit 1;
-    else
-        echo "Your system is not supported. Sorry. Please report us your configuration.";
-        exit 1;
-    fi
-}
-
-check_download_toolchain()
-{
-    if [ ! -d "$SCRIPT_PATH/$TOOLCHAIN_PATH" ]; then
-        download_toolchain;
-    elif [ ! -f "$SCRIPT_PATH/$TOOLCHAIN_PATH/VERSION" ]; then
-        download_toolchain;
-    elif [ "$(cat "$SCRIPT_PATH/$TOOLCHAIN_PATH/VERSION")" -ne "$FLIPPER_TOOLCHAIN_VERSION" ]; then
-        download_toolchain;
-    fi
-}
-
-download_toolchain()
-{
-    chmod 755 "$SCRIPT_PATH/scripts/toolchain/unix-toolchain-download.sh";
-    "$SCRIPT_PATH/scripts/toolchain/unix-toolchain-download.sh" "$FLIPPER_TOOLCHAIN_VERSION" || exit 1;
-}
-
-check_git()
-{
-    if [ ! -d "$SCRIPT_PATH/.git" ]; then
-        echo "\".git\" directory not found, please clone repo via \"git clone --recursive\"";
-        exit 1;
-    fi
-}
-
-get_kernel_type;  # sets TOOLCHAIN_PATH
-check_git;
-check_download_toolchain;
 git submodule update --init;
-PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/python/bin:$PATH";
-PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/bin:$PATH";
-PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/protobuf/bin:$PATH";
-PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/openocd/bin:$PATH";
 
-"$SCRIPT_PATH/$TOOLCHAIN_PATH/python/bin/python3" "$SCRIPT_PATH/lib/scons/scripts/scons.py" $SCONS_DEFAULT_FLAGS "$@"
+SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built";
+python3 "$SCRIPT_PATH/lib/scons/scripts/scons.py" $SCONS_DEFAULT_FLAGS "$@"
