fbt: Restored old ep git handling

diff --git a/fbt b/fbt
--- a/fbt
+++ b/fbt
@@ -6,7 +6,16 @@ SCRIPTDIR="$( dirname -- "$0"; )";
 SCONS_EP=${SCRIPTDIR}/lib/scons/scripts/scons.py
 
 if [[ -d .git ]]; then
-    python3 ${SCONS_EP} -Q --git-tasks submodule_update
+	#if [[ -d SCONS_EP ]] ; then
+	#	python3 ${SCONS_EP} -Q --git-tasks submodule_update
+	#else
+		echo "Updating git submodules"
+		git submodule update --init
+	#fi
+else # Not in a git repo
+    echo "Not in a git repo, please clone with git clone --recursive"
+    # Return error code 1 to indicate failure
+    exit 1
 fi
 
 SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built"
