fix merge conflicts

diff --git a/fbt b/fbt
--- a/fbt
+++ b/fbt
@@ -1,13 +1,22 @@
 #!/bin/sh
-SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)";
-. $SCRIPT_PATH/scripts/toolchain/fbtenv.sh;
 
-if [ ! -d "${FBT_ROOT:-.}/.git" ]; then
-    echo "\".git\" directory not found, please clone repo via \"git clone --recursive\"";
-    exit 1;
-fi
-
-git submodule update --init;
+# shellcheck disable=SC2086 source=/dev/null
+# unofficial strict mode
+set -eu;
 
 SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built";
+SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)";
+
+if [ -z "${FBT_NOENV:-}" ]; then
+    . "$SCRIPT_PATH/scripts/toolchain/fbtenv.sh";
+fi
+
+if [ -z "${FBT_NO_SYNC:-}" ]; then
+    if [ ! -d "$SCRIPT_PATH/.git" ]; then
+        echo "\".git\" directory not found, please clone repo via \"git clone --recursive\"";
+        exit 1;
+    fi
+    git submodule update --init;
+fi
+
 python3 "$SCRIPT_PATH/lib/scons/scripts/scons.py" $SCONS_DEFAULT_FLAGS "$@"
