add checking .git directory

diff --git a/fbt b/fbt
--- a/fbt
+++ b/fbt
@@ -23,23 +23,25 @@ get_kernel_type()
 download_toolchain()
 {
     if [ ! -d "$SCRIPT_PATH/$TOOLCHAIN_PATH" ]; then
+        chmod 755 "scripts/toolchain/unix-toolchain-download.sh";
         scripts/toolchain/unix-toolchain-download.sh || exit 1;
     fi
 }
 
-download_submodules()
+check_git()
 {
-    if [ -d .git ]; then
-        git submodule init
-        git submodule update
+    if [ ! -d "$SCRIPT_PATH/.git" ]; then
+        echo "\".git\" directory not found, please clone repo via \"git clone\"";
+        exit 1;
     fi
 }
 
 SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd -P)"
 SCONS_DEFAULT_FLAGS="-Q --warn=target-not-built";
 get_kernel_type;
+check_git;
 download_toolchain;
-download_submodules;
+git submodule update --init;
 PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/python/bin:$PATH";
 PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/bin:$PATH";
 PATH="$SCRIPT_PATH/$TOOLCHAIN_PATH/protobuf/bin:$PATH";
